spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://myopenbk:5432/openbk"
    username: any
    password: any
    ddl-auto: create

server:
  port: 8000
  compression:
    enabled: true
    mime-types: application/json
