spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    ddl-auto: create

server:
  port: 8000
  compression:
    enabled: true
    mime-types: application/json
