docker:
  host: "${DOCKER_IP:localhost}"
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: 'jdbc:postgresql://${docker.host}:5432/myopenbk'
    username: "userdb"
    password: "passdb"
    dbname: "myopenbk"

server:
  port: 8000
  compression:
    enabled: true
    mime-types: application/json
